# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stefano
email: stefano.cassio@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog where I post useful information I have gatherd which can be 
  from cool designs and projects to useful commands and tips that I've learnt 
  and don't want to forget.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stefano.cassio.1
github_username:  stefanobkk

# Build settings
markdown: kramdown
